version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: PostgresLastest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: igv0374
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: PgAdminLastest
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: rubensfacco94@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 12354
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: ambiente_default
    external: true
